<?php
echo '<!doctype html>';
echo '<html class="no-js" lang="">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<title>Home | Isis Gonçalves Photography</title>';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">';
echo '<link rel="stylesheet" type="text/css" href="slick.css"/>';
echo '<link rel="stylesheet" type="text/css" href="slick-theme.css"/>';
echo '<link rel="stylesheet" href="css/styles_isis.css">';
echo '';
echo '<meta name="description" content="">';
echo '';
echo '<meta property="og:title" content="">';
echo '<meta property="og:type" content="">';
echo '<meta property="og:url" content="">';
echo '<meta property="og:image" content="">';
echo '';
echo '<link rel="icon" href="favicon.ico" sizes="any">';
echo '<link rel="icon" href="favicon-32x32.png" type="image/svg+xml">';
echo '<link rel="apple-touch-icon" href="favicon-16x16.png">';
echo '';
echo '<link rel="manifest" href="site.webmanifest">';
echo '<meta name="theme-color" content="#fafafa">';
echo '</head>';
echo '<body class="expand">';
echo '<header>';
echo '<div class="container-fluid p-1 p-sm-3 header-container">';
echo '<div class="row d-flex align-items-center header-content">';
echo '<a class="col-5 col-sm-4 col-md-2 logo clean d-flex justify-content-center" href="index.html">';
echo '<h1>ISIS <br> GONÇALVES</h1>';
echo '</a>';
echo '<div class="col-8 menu-home">';
echo '<div class="d-flex justify-content-around align-items-center header-border p-2">';
echo '<!-- <button class="arrow d-flex justify-content-center clean hover">';
echo '<img src="images/arr_l.svg">';
echo '</button> -->';
echo '<a class="hover clean fix-width-menu" href="editorial_gallery.html">';
echo '<h3>editorial</h3>';
echo '</a>';
echo '<div class="d-flex pt-1">';
echo '<div class="dot"></div>';
echo '</div>';
echo '<a class="hover clean fix-width-menu" href="lifestyle_gallery.html">';
echo '<h3>lifestyle</h3>';
echo '</a>';
echo '<div class="d-flex pt-1">';
echo '<div class="dot"></div>';
echo '</div>';
echo '<a class="hover clean fix-width-menu" href="wedding_gallery.html">';
echo '<h3>wedding</h3>';
echo '</a>';
echo '<!-- <button class="arrow d-flex justify-content-center clean hover">';
echo '<img src="images/arr_r.svg">';
echo '</button> -->';
echo '</div>';
echo '</div>';
echo '<!-- <div class="col-8 menu-home">';
echo '<div class="d-flex justify-content-around align-items-center header-border p-2">';
echo '<button class="arrow d-flex justify-content-center clean hover">';
echo '<img src="images/arr_l.svg">';
echo '</button>';
echo '<a class="hover clean" href="editorial.html">';
echo '<h3>editorial</h3>';
echo '</a>';
echo '<div class="d-flex pt-1">';
echo '<div class="dot"></div>';
echo '</div>';
echo '<a class="hover clean" href="lifestyle.html">';
echo '<h3>lifestyle</h3>';
echo '</a>';
echo '<div class="d-flex pt-1">';
echo '<div class="dot"></div>';
echo '</div>';
echo '<a class="hover clean" href="wedding.html">';
echo '<h3>wedding</h3>';
echo '</a>';
echo '<button class="arrow d-flex justify-content-center clean hover">';
echo '<img src="images/arr_r.svg">';
echo '</button>';
echo '</div>';
echo '</div> -->';
echo '<button class="offset-3 offset-sm-6 offset-md-0 col-4 col-sm-2 col-xs-3 hover menu clean d-flex justify-content-end justify-content-sm-center">';
echo '<h3 class="word-menu expand">menu</h3>';
echo '<h3 class="x-menu expand pe-3 pe-sm-0">X</h3>';
echo '</button>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<div class="expand full-menu d-flex justify-content-around align-items-center flex-column">';
echo '<div class="d-md-none d-flex flex-column justify-content-center align-items-center pt-5">';
echo '<h2>GALLERIES</h2>';
echo '<a href="editorial_gallery.html">editorial</a>';
echo '<a href="lifestyle_gallery_gallery.html">lifestyle</a>';
echo '<a href="wedding_gallery.html_gallery.html">wedding</a>';
echo '</div>';
echo '<div class="d-flex justify-content-center flex-column align-items-center pb-5">';
echo '<h2 class="d-md-none">OTHER</h2>';
echo '<button class="hover scroll-about">about</button>';
echo '<button class="hover scroll-testimonials">testimonials</button>';
echo '<button class="hover scroll-contact">contact</button>';
echo '<button class="hover scroll-instagram">instagram</button>';
echo '</div>';
echo '<!-- <button>X</button> -->';
echo '</div>';
echo '<main class="index-portfolio">';
echo '<section class="container-fluid index-carousel-container p-0">';
echo '<div class="bg-white"></div>';
echo '<div class="index-carousel">';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/LIFESTYLE/000008.JPG">';
echo '</div>';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/PORTRAITS/000009.jpg">';
echo '</div>';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/WEDDINGS/AA_24-10.jpg">';
echo '</div>';
echo '</div>';
echo '<div class="fading"></div>';
echo '<div class="elements-hero abs container-fluid">';
echo '<div class="main-title logo animate-me">';
echo '<h1>ISIS <br>GONÇALVES</h1>';
echo '</div>';
echo '<div class="container-fluid themes py-5">';
echo '<div class="row d-flex align-items-center justify-content-center">';
echo '<div class="col-md-8 col-sm-10 col-12 menu-main animate-me">';
echo '<div class="d-flex justify-content-around align-items-center p-md-2">';
echo '<!-- <button class="arrow d-flex justify-content-center clean hover">';
echo '<img src="images/arr_l_w.svg">';
echo '</button> -->';
echo '<a class="hover clean fix-width-menu" href="editorial_gallery.html">';
echo '<h3>editorial</h3>';
echo '</a>';
echo '<div class="d-flex pt-1">';
echo '<div class="dot"></div>';
echo '</div>';
echo '<a class="hover clean fix-width-menu" href="lifestyle_gallery.html">';
echo '<h3>lifestyle</h3>';
echo '</a>';
echo '<div class="d-flex pt-1">';
echo '<div class="dot"></div>';
echo '</div>';
echo '<a class="hover clean fix-width-menu" href="wedding_gallery.html">';
echo '<h3>wedding</h3>';
echo '</a>';
echo '<!-- <button class="arrow d-flex justify-content-center clean hover">';
echo '<img src="images/arr_r_w.svg">';
echo '</button> -->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="animate-me">';
echo '<h3>photography</h3>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '<section class="about-container container-fluid px-0">';
echo '<div class="text-container animate-me">';
echo '<div class="text-margin">';
echo '<div>';
echo '<h4 class="pb-xxl-3 pb-3">';
echo 'I believe I was not gifted with the power of words, but that realisation is what';
echo 'drew me to photography in the first place, especially film photography.';
echo '</h4>';
echo '</div>';
echo '<div>';
echo '<p>';
echo 'I create through capturing not just what looks beautiful, but everything that';
echo 'evokes some kind of emotion within me. I also love to get to know the people I';
echo 'photograph. Once we establish a connection, everything flows much more naturally.';
echo '</p>';
echo '<p>';
echo 'In recent years, I’ve primarily focused my work on weddings, portraits, and';
echo 'editorial shoots. However, if you’re looking for a different type of photography,';
echo 'please feel free to reach out to me.';
echo '</p>';
echo '<p>';
echo 'When it comes to weddings, you can count on me to capture your special day in the';
echo 'best way possible, staying true to the emotions of the event and providing you';
echo 'with a stunning gallery. You can also expect my full support and guidance to help';
echo 'smooth out the day. If you consider yourselves a warm, loving, modern couple, I';
echo 'believe we will get along very well.';
echo '</p>';
echo '<p class="mb-0">With love,</p>';
echo '<p class="mb-0 bng">';
echo 'ISIS';
echo '';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="img-container">';
echo '<div class="img-box-1">';
echo '<img src="images/ME/1-3.jpg">';
echo '</div>';
echo '<div class="carousel-box-1 animate-me">';
echo '<div class="about-carousel">';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/WEDDINGS/AA_24-2.jpg">';
echo '</div>';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/PORTRAITS/0810-19.jpg">';
echo '</div>';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/WEDDINGS/rnreedit-37.jpg">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-box-2 animate-me">';
echo '<div class="about-carousel">';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/LIFESTYLE/000017-2.jpg">';
echo '</div>';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/PORTRAITS/bb2.jpg">';
echo '</div>';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/WEDDINGS/IP-54.jpg">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="carousel-box-3 animate-me">';
echo '<div class="about-carousel">';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/PORTRAITS/0815400-39.jpg">';
echo '</div>';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/PORTRAITS/alice-40.jpg">';
echo '</div>';
echo '<div class="slide d-flex justify-content-center">';
echo '<img src="images/WEDDINGS/AA_24-34.jpg">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="title-container animate-me" style="mix-blend-mode: exclusion;">';
echo '<div class="segment-title pe-3">';
echo '<h2 class="px-3">ABOUT</h2>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<section class="testimonials-container container-fluid px-0">';
echo '<div class="title-container animate-me">';
echo '<div class="segment-title pe-3">';
echo '<h2 class="px-3">TESTIMONIALS</h2>';
echo '<div class="button-carousel"></div>';
echo '</div>';
echo '</div>';
echo '<div class="testimonials-carousel px-2 px-sm-4 animate-me">';
echo '<div class="slide d-flex">';
echo '<div class="testimonial-gradient d-lg-none"></div>';
echo '<div class="testimonial-photo-container d-flex">';
echo '<img src="images/WEDDINGS/AA_24-10.jpg">';
echo '</div>';
echo '<div class="testimonial-text-container px-4 px-sm-0">';
echo '<div class="testimonials-text">';
echo '<h4 class="mb-0">';
echo '“(…) We really loved the gallery! Isis did a stunning work. She is amazing and was born for this, indeed!”';
echo '</h4>';
echo '<p class="mb-0 mt-3 bng">';
echo '-S & R';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="slide d-flex">';
echo '<div class="testimonial-gradient d-lg-none"></div>';
echo '<div class="testimonial-photo-container d-flex">';
echo '<img src="images/WEDDINGS/wedm-1.jpg">';
echo '</div>';
echo '<div class="testimonial-text-container px-4 px-sm-0">';
echo '<div class="testimonials-text">';
echo '<h4 class="mb-0">';
echo '“(…)We just saw the photos, and everything looks marvelous! Thank you so much!';
echo 'Our wedding was captured beautifully! We will definitely contact Isis again in the';
echo 'future and recommend her whenever someone needs photography services.”';
echo '</h4>';
echo '<p class="mb-0 mt-3 bng">';
echo '-S & M';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="slide d-flex">';
echo '<div class="testimonial-gradient d-lg-none"></div>';
echo '<div class="testimonial-photo-container d-flex">';
echo '<img src="images/WEDDINGS/IP-9.jpg">';
echo '</div>';
echo '<div class="testimonial-text-container px-4 px-sm-0">';
echo '<div class="testimonials-text">';
echo '<h4 class="mb-3">';
echo '“Isis is incredible. She is exceptionally talented and professional, with a remarkable';
echo 'ability to pay attention to detail. We hired her as our wedding photographer, and the';
echo 'results were nothing short of perfect.';
echo '</h4>';
echo '<p class="mt-3">';
echo '(...) She understood our wishes, helped keep us';
echo 'calm, and transformed what could have been a tedious experience of taking 1,000';
echo 'photographs into something smooth and enjoyable. The way she captured our special day';
echo 'was outstanding. We wholeheartedly recommend her work to anyone looking to hire a rising';
echo 'star in photography!”';
echo '</p>';
echo '<p class="mb-0 mt-3 bng">';
echo '-E & C';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- <div class="button-container">';
echo '<div class="button-carousel"></div>';
echo '</div> -->';
echo '</section>';
echo '<section class="contact-container">';
echo '<div class="text-container animate-me">';
echo '<div class="text-margin">';
echo '<div>';
echo '<h4 class="pb-xxl-3 pb-3">';
echo 'Looking for the right person to photograph your wedding?';
echo '</h4>';
echo '</div>';
echo '<div>';
echo '<p>';
echo 'I create through capturing not just what looks beautiful, but everything that';
echo 'evokes some kind of emotion within me. I also love to get to know the people I';
echo 'photograph. Once we establish a connection, everything flows much more naturally.';
echo '</p>';
echo '<!-- <p>';
echo 'In recent years, I’ve primarily focused my work on weddings, portraits, and';
echo 'editorial shoots. However, if you’re looking for a different type of photography,';
echo 'please feel free to reach out to me.';
echo '</p>';
echo '<p>';
echo 'When it comes to weddings, you can count on me to capture your special day in the';
echo 'best way possible, staying true to the emotions of the event and providing you';
echo 'with a stunning gallery. You can also expect my full support and guidance to help';
echo 'smooth out the day. If you consider yourselves a warm, loving, modern couple, I';
echo 'believe we will get along very well.';
echo '</p> -->';
echo '<p class="mb-0">With love,</p>';
echo '<p class="mb-0 bng">';
echo 'ISIS';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="form-container animate-me">';
echo '<div class="forms px-2 px-sm-4 py-4">';
echo '<form id="contact-form">';
echo '<h3 class="mb-3">Let's start with your name</h3>';
echo '<input class="mb-5" type="text" name="name" id="client-name" placeholder="Your Name" required />';
echo '';
echo '<h4 class="mb-3">What kind of session are you looking for?</h4>';
echo '<div id="service-selection" class="d-flex justify-content-center flex-wrap">';
echo '<button class="service-btn" type="button" data-service="wedding">Wedding</button>';
echo '<button class="service-btn" type="button" data-service="photoshoot">Photoshoot</button>';
echo '<button class="service-btn" type="button" data-service="editorial">Editorial</button>';
echo '<button class="service-btn" type="button" data-service="baptism">Baptism</button>';
echo '<button class="service-btn" type="button" data-service="other">Other</button>';
echo '</div>';
echo '';
echo '<!-- Wedding form section -->';
echo '<div id="wedding-form-fields" class="service-form">';
echo '<h4 class="mb-3">Wedding Details:</h4>';
echo '<input class="mb-3" type="text" name="partner_name" id="partner-name" placeholder="Your Partner's Name" required />';
echo '<input class="mb-3" type="text" name="location" placeholder="Wedding Location"/>';
echo '<div class="s-input d-flex justify-content-between">';
echo '<input class="mb-3" type="date" name="wedding_date" placeholder="Wedding Date"/>';
echo '<input class="mb-3" type="number" name="number_guests" placeholder="Estimated Number of Guests"/>';
echo '</div>';
echo '<textarea class="mb-5" name="message" placeholder="More about you and your special day..."></textarea>';
echo '<h4 class="mb-3">Fancy some analog photos?</h4>';
echo '<div id="analog-selection" class="d-flex justify-content-center flex-wrap mb-5">';
echo '<button class="analog-btn" type="button" data-value="yes-analog">Yes</button>';
echo '<button class="analog-btn" type="button" data-value="no-analog">No</button>';
echo '<input type="hidden" name="analog_choice" id="analog-choice" required>';
echo '</div>';
echo '<h4 class="mb-3">Your Contact Information:</h4>';
echo '<div class="s-input d-flex justify-content-between">';
echo '<input class="mb-3" type="text" name="email" placeholder="Email Address"/>';
echo '<input class="mb-3" type="text" name="phone" placeholder="Phone Number"/>';
echo '</div>';
echo '<textarea class="mb-5" name="socials" placeholder="Feel free to share your socials!"></textarea>';
echo '<h4 class="mb-3">How did you find about me?</h4>';
echo '<div id="about-me-selection" class="d-flex justify-content-center flex-wrap mb-5">';
echo '<button class="about-me-btn" type="button" data-value="instagram">Instagram</button>';
echo '<button class="about-me-btn" type="button" data-value="facebook">Facebook</button>';
echo '<button class="about-me-btn" type="button" data-value="google">Google</button>';
echo '<button class="about-me-btn" type="button" data-value="reference">Reference</button>';
echo '<button class="about-me-btn" type="button" data-value="casamentos-pt">Casamentos.pt</button>';
echo '<button class="about-me-btn" type="button" data-value="other">Other</button>';
echo '<input type="hidden" name="about_me_choice" id="about-me-choice" required>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Generic event form section -->';
echo '<div id="generic-form-fields" class="service-form">';
echo '<h4 class="mb-3">Service Details</h4>';
echo '<div class="s-input d-flex justify-content-between">';
echo '<input class="mb-3" type="date" name="service_date" placeholder="Date"/>';
echo '<input class="mb-3" type="text" name="location" placeholder="Location"/>';
echo '</div>';
echo '<textarea class="mb-5" name="message" placeholder="More about the service..." required></textarea>';
echo '<h4 class="mb-3">Your Contact Information:</h4>';
echo '<div class="s-input d-flex justify-content-between">';
echo '<input class="mb-5" type="text" name="email" placeholder="Your Email Address"/>';
echo '<input class="mb-5" type="text" name="phone" placeholder="Your Phone Number"/>';
echo '</div>';
echo '<h4 class="mb-3">How did you find about me?</h4>';
echo '<div id="about-me-selection" class="d-flex justify-content-center flex-wrap mb-5">';
echo '<button class="about-me-btn" type="button" data-value="instagram">Instagram</button>';
echo '<button class="about-me-btn" type="button" data-value="facebook">Facebook</button>';
echo '<button class="about-me-btn" type="button" data-value="google">Google</button>';
echo '<button class="about-me-btn" type="button" data-value="reference">Reference</button>';
echo '<button class="about-me-btn" type="button" data-value="casamentos-pt">Casamentos.pt</button>';
echo '<button class="about-me-btn" type="button" data-value="other">Other</button>';
echo '<input type="hidden" name="about_me_choice" id="about-me-choice" required>';
echo '</div>';
echo '</div>';
echo '';
echo '<!-- Submit button (hidden until a service is selected) -->';
echo '<div id="submit-btn" class="d-flex justify-content-center">';
echo '<button type="submit">Send</button>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '<div class="title-container animate-me">';
echo '<div class="segment-title pe-3">';
echo '<h2 class="px-3">CONTACT</h2>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<section class="instagram-container">';
echo '<div class="insta-sum">';
echo '<div class="insta-carousel animate-me">';
echo '<div class="slide">';
echo '<img src="images/LIFESTYLE/000017-2.jpg" alt="Instagram photo 1">';
echo '</div>';
echo '<div class="slide">';
echo '<img src="images/PORTRAITS/sal-33.jpg" alt="Instagram photo 2">';
echo '</div>';
echo '<div class="slide">';
echo '<img src="images/WEDDINGS/rnreedit-37.jpg" alt="Instagram photo 3">';
echo '</div>';
echo '<div class="slide">';
echo '<img src="images/LIFESTYLE/000017-2.jpg" alt="Instagram photo 4">';
echo '</div>';
echo '<div class="slide">';
echo '<img src="images/PORTRAITS/sal-33.jpg" alt="Instagram photo 5">';
echo '</div>';
echo '<div class="slide">';
echo '<img src="images/WEDDINGS/rnreedit-37.jpg" alt="Instagram photo 6">';
echo '</div>';
echo '</div>';
echo '<div class="follow-container d-flex justify-content-center">';
echo '<div class="follow">';
echo '<a class="hover" href="https://www.instagram.com/isistencial/" target="_blank">';
echo '<h3>';
echo 'follow my work';
echo '</h3>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="title-container animate-me w-100">';
echo '<div class="segment-title pe-3">';
echo '<h2 class="px-3">INSTAGRAM</h2>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '</main>';
echo '<footer class="d-flex align-items-center px-1 container-fluid w-100 justify-content-center">';
echo '<div class="d-flex row w-100">';
echo '<div class="d-flex col-12 col-sm-7 col-md-5 col-lg-4 justify-content-around align-items-center">';
echo '<button class="hover scroll-about">';
echo '<h3>about</h3>';
echo '</button>';
echo '<button class="hover scroll-testimonials">';
echo '<h3>testimonials</h3>';
echo '</button>';
echo '<button class="hover scroll-contact">';
echo '<h3>contact</h3>';
echo '</button>';
echo '</div>';
echo '<div class="d-none d-lg-block col-lg-4">';
echo '<!-- <button class="back hover">';
echo '<img src="images/seta_thin.svg">';
echo '</button> -->';
echo '</div>';
echo '<div class="d-none d-sm-flex col-5 col-md-7 col-lg-4 pt-2 justify-content-end">';
echo '<a class="logo clean" href="index.html">';
echo '<h1>ISIS <br> GONÇALVES</h1>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '<script src="https://code.jquery.com/jquery-3.7.1.min.js"';
echo 'integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"';
echo 'integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>';
echo '<script type="text/javascript" src="slick.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"';
echo 'integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="';
echo 'crossorigin="anonymous" referrerpolicy="no-referrer"></script>';
echo '<script src="js/portfolio_java.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>